switch to dfl
https://github.com/elentok/dfl

diff --git a/core/nodejs/install b/core/nodejs/install
--- a/core/nodejs/install
+++ b/core/nodejs/install
@@ -2,28 +2,26 @@
 
 set -euo pipefail
 
-source "$(dirname "$0")/../../framework.sh"
+NODE_VER=24
 
-main() {
-  install_fnm
+dfl step start "Installing node..."
+if ! dfl has-command fnm; then
+  dfl step error "fnm is missing, it should have been installed with brew"
+  return
+fi
 
-  if dotf-command-missing yarn; then
-    npm install -g yarn
-  fi
+eval "$(fnm env --use-on-cd)"
+
+function has-version() {
+  fnm list | grep " v${1}\." >/dev/null
 }
 
-install_fnm() {
-  if dotf-command-missing fnm; then
-    dotf-error "fnm is missing, it should have been installed with brew"
-    exit 1
-  fi
+if has-version $NODE_VER; then
+  dfl step skip "Node $NODE_VER already installed"
+else
+  fnm install "$NODE_VER" &&
+    dfl step success "Installed Node $NODE_VER" ||
+    dfl step error "Failed to install Node $NODE_VER"
+fi
 
-  eval "$(fnm env --use-on-cd)"
-
-  ver="$(dotf-node-version)"
-  if ! fnm list | grep " v$ver\." >/dev/null; then
-    fnm install "$(dotf-node-version)"
-  fi
-}
-
-main "$@"
+dfl pkg npm install cloc fx json live-server yarn markserv neovim
